  version: "3.8"
  services:
    backend:
      container_name: acmebankportal
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - FS_API_URL_V1=http://localhost:8001/financialservice/api/v1.0
        - US_API_URL_V1=http://localhost:8002/userservice/api/v1.0
      command: "python run.py runserver 0.0.0.0:8000"
      ports:
        - 8000:8000
      volumes:
        - .:/app