  version: "3.8"
  services:
    backend:
      container_name: acmebankportal
      build:
        context: .
        dockerfile: Dockerfile
      networks:
        - acmebankportal_network
      environment:
        - FS_API_URL_V1=http://fs_backend:8001/financialservice/api/v1.0
        - US_API_URL_V1=http://us_backend:8002/userservice/api/v1.0
      command: "python run.py runserver 0.0.0.0:8000"
      ports:
        - 8000:8000
      volumes:
        - .:/app

  networks:
    acmebankportal_network:
      name: acmebankportal_default
      driver: bridge